### ISSUE TITLE
Building with Android studio 4.0

### ISSUE THREAD

**Issue by YileKu** [bastibl/android-hw#1]
Good work on this app.

I get this error when I try to build it in Android Studio 4.0:

Minimum supported Gradle version is 6.1.1. Current version is 5.6.4.

Please fix the project's Gradle settings.
Fix Gradle wrapper and re-import project
Open Gradle wrapper properties
Gradle settings

**Comment by bastibl** [comment]
Where exactly does this show up? Aren't these actions that you posted links/buttons to do automatically? Did you already click on them (e.g.  Fix Gradle wrapper and re-import project)?

**Comment by YileKu** [comment]
Bastian,

It was my issue.  Sorry about the confusion.  I think this project is
excellent.  I hope you don't mind me pinging you with the odd question...
Thanks,
Y-

**Comment by bastibl** [comment]
no worries. I'm happy it's solved. I'm closing the issue.
